ALTER TABLE event MODIFY task_id INT(11);
ALTER TABLE event MODIFY deleted TINYINT(1) default 0;
ALTER TABLE event ADD COLUMN old_value VARCHAR(255);
ALTER TABLE event ADD COLUMN created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE event ADD COLUMN date DATE NOT NULL DEFAULT CURRENT_DATE;
